// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwsxyspawvzvbkqwtyqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3c3h5c3Bhd3Z6dmJrcXd0eXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODYxNzAsImV4cCI6MjA2ODk2MjE3MH0.3cRQIAWw8KR-O4C-ym4OpzNdLczQd6G2o7NmkDKKrw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});